// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/1/2026, 3:40:01 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/mac/Documents/new-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/new-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/new-portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/new-portfolio/plugins/**/*.{js,ts,mjs}","/Users/mac/Documents/new-portfolio/composables/**/*.{js,ts,mjs}","/Users/mac/Documents/new-portfolio/utils/**/*.{js,ts,mjs}","/Users/mac/Documents/new-portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/new-portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/new-portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/new-portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;