// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/20/2025, 3:31:14 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/hp/Documents/portfolio-ayodeji/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Documents/portfolio-ayodeji/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Documents/portfolio-ayodeji/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Documents/portfolio-ayodeji/plugins/**/*.{js,ts,mjs}","C:/Users/hp/Documents/portfolio-ayodeji/composables/**/*.{js,ts,mjs}","C:/Users/hp/Documents/portfolio-ayodeji/utils/**/*.{js,ts,mjs}","C:/Users/hp/Documents/portfolio-ayodeji/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Documents/portfolio-ayodeji/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Documents/portfolio-ayodeji/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/Documents/portfolio-ayodeji/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;